### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by morbidick** [morbidick/card10-pwa#1]
Meta Issue to keep track of all the cool things to be done

* [x] basic interactions (led, clock)
* [x] svg card face
* [ ] disconnect handler
* [ ] offline support / installable
  * [ ] service worker
  * [ ] manifest
  * [ ] opengraph metatags
* [ ] vibration
* [ ] add UTC set clock button
* [ ] allow mood selection
* [ ] get led strip running
* [ ] implement file protocol
* [ ] ECG viewer
* [ ] file upload
* [ ] web ide
